/**
 * Mapping of Chinese diagnostic values (stored in DB) to English translations.
 * Used for company diagnostic tags in Report and Companies pages.
 */
const zhToEn: Record<string, string> = {
  // Strategic Positioning
  '开拓者': 'Pioneer',
  '稳固者': 'Stabilizer',
  '分红者': 'Dividend Payer',
  // Market Cap Size
  '实力股': 'Large Cap',
  '潜力股': 'Mid Cap',
  '弹簧股': 'Small Cap',
  // Cyclical Nature
  '防御型': 'Defensive',
  '周期型': 'Cyclical',
  '探险型': 'Adventurous',
  // Cash Flow Status
  '健康型': 'Healthy',
  '贫血型': 'Anemic',
  // Debt Structure
  '轻装型': 'Low Leverage',
  '平衡型': 'Balanced',
  '背债型': 'Heavy Debt',
  // External Sensitivity
  '政策型': 'Policy-driven',
  '汇率型': 'FX-sensitive',
  '内功型': 'Self-driven',
  // Profit Model
  '薄利多销型': 'Thin Margin',
  '高利少销型': 'High Margin',
  '坐地收租型': 'Rent Seeking',
  '烧钱圈地型': 'Cash Burn',

  // Report diagnostic tags (generated by computeDiagnosticTags)
  // Industry Outlook
  '政策扶持': 'Policy Supported',
  '朝阳行业': 'Sunrise Industry',
  '夕阳行业': 'Sunset Industry',
  '成熟行业': 'Mature Industry',
  // Industry Position
  '行业垄断': 'Monopoly',
  '行业龙头': 'Industry Leader',
  '第二梯队': 'Second Tier',
  '边缘玩家': 'Marginal Player',
  // Operations
  '转型中': 'Restructuring',
  '经营优秀': 'Excellent Ops',
  '经营困难': 'Struggling',
  '经营平稳': 'Stable Ops',
  // Growth Momentum
  '巨无霸': 'Giant',
  '高速成长': 'High Growth',
  '增长乏力': 'Slowing',
  '稳健增长': 'Steady Growth',
  // Scale
  '万亿巨头': 'Trillion Club',
  '大型企业': 'Large Enterprise',
  '中型企业': 'Mid Enterprise',
  '小型企业': 'Small Enterprise',

  // Dimension names
  '行业前景': 'Industry Outlook',
  '行业地位': 'Industry Position',
  '经营情况': 'Operations',
  '发展势头': 'Growth Momentum',
  '目前体量': 'Scale',
};

/**
 * Translate a Chinese diagnostic value to English.
 * Returns the original value if no translation is found.
 */
export function translateDiagnosticTag(value: string, locale: string): string {
  if (locale === 'zh' || !value) return value;
  return zhToEn[value] || value;
}
