/**
 * Mapping of Chinese diagnostic values (stored in DB) to English translations.
 * Used for company diagnostic tags in Report and Companies pages.
 */
const zhToEn: Record<string, string> = {
  // Strategic Positioning
  '开拓者': 'Pioneer',
  '稳固者': 'Stabilizer',
  '分红者': 'Dividend Payer',
  // Market Cap Size
  '实力股': 'Large Cap',
  '潜力股': 'Mid Cap',
  '弹簧股': 'Small Cap',
  // Cyclical Nature
  '防御型': 'Defensive',
  '周期型': 'Cyclical',
  '探险型': 'Adventurous',
  // Cash Flow Status
  '健康型': 'Healthy',
  '贫血型': 'Anemic',
  // Debt Structure
  '轻装型': 'Low Leverage',
  '平衡型': 'Balanced',
  '背债型': 'Heavy Debt',
  // External Sensitivity
  '政策型': 'Policy-driven',
  '汇率型': 'FX-sensitive',
  '内功型': 'Self-driven',
  // Profit Model
  '薄利多销型': 'Thin Margin',
  '高利少销型': 'High Margin',
  '坐地收租型': 'Rent Seeking',
  '烧钱圈地型': 'Cash Burn',

  // Report diagnostic tags (generated by computeDiagnosticTags)
  // Industry Outlook
  '政策扶持': 'Policy Supported',
  '朝阳行业': 'Sunrise Industry',
  '夕阳行业': 'Sunset Industry',
  '成熟行业': 'Mature Industry',
  // Industry Position
  '行业垄断': 'Monopoly',
  '行业龙头': 'Industry Leader',
  '第二梯队': 'Second Tier',
  '边缘玩家': 'Marginal Player',
  // Operations
  '转型中': 'Restructuring',
  '经营优秀': 'Excellent Ops',
  '经营困难': 'Struggling',
  '经营平稳': 'Stable Ops',
  // Growth Momentum
  '巨无霸': 'Giant',
  '高速成长': 'High Growth',
  '增长乏力': 'Slowing',
  '稳健增长': 'Steady Growth',
  // Scale
  '万亿巨头': 'Trillion Club',
  '大型企业': 'Large Enterprise',
  '中型企业': 'Mid Enterprise',
  '小型企业': 'Small Enterprise',

  // Dimension names
  '行业前景': 'Industry Outlook',
  '行业地位': 'Industry Position',
  '经营情况': 'Operations',
  '发展势头': 'Growth Momentum',
  '目前体量': 'Scale',
};

/**
 * Translate a Chinese diagnostic value to English.
 * Returns the original value if no translation is found.
 */
export function translateDiagnosticTag(value: string, locale: string): string {
  if (locale === 'zh' || !value) return value;
  return zhToEn[value] || value;
}

/**
 * Diagnostic dimension keys (snake_case base name in the DB).
 */
export type DiagnosticDimensionField =
  | 'strategic_positioning'
  | 'market_cap_size'
  | 'cyclical_nature'
  | 'cash_flow_status'
  | 'debt_structure'
  | 'external_sensitivity'
  | 'profit_model';

/**
 * Read a localized diagnostic dimension value from a company_diagnostics row.
 *
 * The DB now exposes both the legacy Chinese column (e.g. `strategic_positioning`)
 * and explicit bilingual columns (`strategic_positioning_zh` / `_en`). Pick the
 * column matching the requested locale; fall back to the other locale's column,
 * then to the legacy column, finally to a hardcoded translation map.
 */
export function getLocalizedDiagnostic(
  company: Record<string, any> | null | undefined,
  field: DiagnosticDimensionField,
  locale: string,
): string | null {
  if (!company) return null;
  const wantEn = locale === 'en';
  const primary = wantEn ? company[`${field}_en`] : company[`${field}_zh`];
  if (primary) return primary as string;

  const secondary = wantEn ? company[`${field}_zh`] : company[`${field}_en`];
  const legacy = company[field];

  if (wantEn) {
    if (legacy) {
      const translated = zhToEn[legacy as string];
      if (translated) return translated;
    }
    if (secondary) return secondary as string;
    return (legacy as string) || null;
  }

  return (legacy as string) || (secondary as string) || null;
}

/**
 * Read the localized AI reasoning text from a company_diagnostics row.
 * Falls back through `_en` / `_zh` / legacy `ai_reasoning` according to locale.
 */
export function getLocalizedReasoning(
  company: Record<string, any> | null | undefined,
  locale: string,
): string | null {
  if (!company) return null;
  const wantEn = locale === 'en';
  const primary = wantEn ? company.ai_reasoning_en : company.ai_reasoning_zh;
  if (primary) return primary as string;
  const secondary = wantEn ? company.ai_reasoning_zh : company.ai_reasoning_en;
  if (wantEn) {
    return (secondary as string) || (company.ai_reasoning as string) || null;
  }
  return (company.ai_reasoning as string) || (secondary as string) || null;
}
